#!/bin/bash
echo ""
echo "=== Begin Pushing ==="
echo ""

echo ">>> These are done simulataneously..."
git push origin master &
git push github-backup master &
git push home master

echo ""
echo "=== Pushes Complete ==="
echo ""
