#!/bin/bash
echo ""
echo "=== Begin Pushing ==="
echo ""

echo ">>> These are done simulataneously..."
( echo "Bitbucket First..." && git push -qqq origin master && echo "Bitbucket is Done!" ) &
( echo "Github Next..." && git push -qqq github-backup master && echo "Github is Done!" ) &
( echo "Home Gitea Last..." && git push -qqq home master && echo "Home Backup is Done!" )

echo ""
echo "=== Pushes Complete ==="
echo ""
